com.fasterxml.jackson.*:* = 2.20.0
com.fasterxml.jackson.core:jackson-annotations = 2.20
com.google.auto.service:* = 1.1.1
com.palantir.docker.compose:* = 2.3.0
junit:junit = 4.13.2
one.util:streamex = 0.8.4
org.assertj:assertj-core = 3.27.6
org.junit.jupiter:* = 6.0.1
org.mockito:* = 5.20.0
org.hamcrest:* = 2.1
net.bytebuddy:* = 1.17.8
