com.fasterxml.jackson.*:* = 2.21.1
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.google.auto.service:* = 1.1.1
com.palantir.docker.compose:* = 2.3.0
junit:junit = 4.13.2
one.util:streamex = 0.8.4
org.assertj:assertj-core = 3.27.7
org.junit.jupiter:* = 5.8.2
org.mockito:* = 4.4.0
org.hamcrest:* = 2.1
net.bytebuddy:* = 1.18.8
